CREATE TABLE [track].[Log]
( [LogId] INT NOT NULL IDENTITY(1,1) PRIMARY KEY
, CreatedDateTime DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
, [Message] NVARCHAR(max) NOT NULL
, [Exception] NVARCHAR(max) NOT NULL
)
